version: "3.8"

services:
  kedro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kedro_project
    ports:
      - "8888:8888" # Expose port 8888 for Jupyter Notebook or Kedro UI
    volumes:
      - ./data:/home/kedro_docker/data # Mount the data directory for persistence
      - ./logs:/home/kedro_docker/logs # Mount the logs directory for persistence
      - ./notebooks:/home/kedro_docker/notebooks # Mount the notebooks directory
      - ./conf:/home/kedro_docker/conf # Mount the configuration directory
    environment:
      - PYTHONUNBUFFERED=1 # Ensure Python output is not buffered
    command: ["kedro", "run"] # Default command to run the Kedro pipeline